#include "PlainTextParser.h"

#include <FS.h>          // v2.0.189 — Arduino File for LittleFS reads
#include <LittleFS.h>    // v2.0.189 — cp1251 cache lives on LittleFS
#include <GfxRenderer.h>
#include <Logging.h>
#include <Page.h>
#include <ParsedText.h>
#include <SDCardManager.h>
#include <Utf8.h>

#define TAG "TXT_PARSE"

#include <utility>

namespace {
constexpr size_t READ_CHUNK_SIZE = 4096;

bool isWhitespace(char c) { return c == ' ' || c == '\r' || c == '\n' || c == '\t'; }

// v2.0.189 — tiny RAII wrapper that abstracts SD (FsFile) vs LittleFS
// (Arduino File) so parsePages() reads through ONE interface
// regardless of which FS holds the actual content.  Lifetime is
// scoped to a single parsePages() invocation; close() runs on
// destruction so early returns can't leak a file handle.
//
// Why not Stream*?  FsFile and Arduino's File don't share a Stream
// base — they're independent class hierarchies that happen to expose
// similar member-function names.  Tagged union is the smallest correct
// abstraction; vtables would cost a heap alloc per parse call.
class AnyFile {
 public:
  AnyFile() = default;
  AnyFile(const AnyFile&) = delete;
  AnyFile& operator=(const AnyFile&) = delete;
  ~AnyFile() { close(); }

  bool openSd(const std::string& path) {
    if (!SdMan.openFileForRead("TXT", path, sdFile_)) return false;
    useLittleFs_ = false;
    open_ = true;
    return true;
  }
  bool openLittleFs(const std::string& path) {
    lfsFile_ = LittleFS.open(path.c_str(), "r");
    if (!lfsFile_) return false;
    useLittleFs_ = true;
    open_ = true;
    return true;
  }

  size_t size() { return useLittleFs_ ? lfsFile_.size() : sdFile_.size(); }
  size_t position() { return useLittleFs_ ? lfsFile_.position() : sdFile_.position(); }
  // SdFat's seek() (absolute) is `bool seek(uint64_t)`; Arduino File's
  // is `bool seek(uint32_t)`.  Both accept the size_t value safely.
  bool seek(size_t pos) { return useLittleFs_ ? lfsFile_.seek(pos) : sdFile_.seek(pos); }
  // SdFat exposes seekSet explicitly; Arduino File uses seek(pos, SeekSet).
  bool seekSet(size_t pos) {
    return useLittleFs_ ? lfsFile_.seek(pos, SeekSet) : sdFile_.seekSet(pos);
  }
  int read(uint8_t* buf, size_t len) {
    return useLittleFs_ ? lfsFile_.read(buf, len) : sdFile_.read(buf, len);
  }
  int available() { return useLittleFs_ ? lfsFile_.available() : sdFile_.available(); }
  void close() {
    if (!open_) return;
    if (useLittleFs_) {
      lfsFile_.close();
    } else {
      sdFile_.close();
    }
    open_ = false;
  }

 private:
  FsFile sdFile_;
  File lfsFile_;
  bool useLittleFs_ = false;
  bool open_ = false;
};
}  // namespace

PlainTextParser::PlainTextParser(std::string filepath, GfxRenderer& renderer, const RenderConfig& config,
                                 bool useLittleFs)
    : filepath_(std::move(filepath)), renderer_(renderer), config_(config), useLittleFs_(useLittleFs) {}

void PlainTextParser::reset() {
  currentOffset_ = 0;
  hasMore_ = true;
  isRtl_ = false;
  pendingBlock_.reset();
  pendingPage_.reset();
  pendingPageY_ = 0;
}

bool PlainTextParser::parsePages(const std::function<void(std::unique_ptr<Page>)>& onPageComplete, uint16_t maxPages,
                                 const AbortCallback& shouldAbort) {
  // v2.0.189 — route through AnyFile so the same loop works whether
  // the file lives on SD (default) or LittleFS (UTF-8 cache for a
  // cp1251 source, generated by Txt::load()).  `useLittleFs_` is set
  // by the constructor based on the caller's knowledge of the Txt
  // object's effective content path.
  AnyFile file;
  const bool opened = useLittleFs_ ? file.openLittleFs(filepath_) : file.openSd(filepath_);
  if (!opened) {
    LOG_ERR(TAG, "Failed to open file (%s): %s",
            useLittleFs_ ? "LittleFS" : "SD", filepath_.c_str());
    return false;
  }

  fileSize_ = file.size();
  if (currentOffset_ > 0) {
    file.seek(currentOffset_);
  }

  const int lineHeight = static_cast<int>(renderer_.getEffectiveLineHeight(config_.fontId) * config_.lineCompression);
  const int maxLinesPerPage = config_.viewportHeight / lineHeight;

  uint8_t buffer[READ_CHUNK_SIZE + 1];
  std::unique_ptr<ParsedText> currentBlock;
  std::unique_ptr<Page> currentPage;
  int16_t currentPageY = 0;
  uint16_t pagesCreated = 0;
  std::string partialWord;
  uint16_t abortCheckCounter = 0;

  auto startNewPage = [&]() {
    currentPage.reset(new Page());
    currentPageY = 0;
  };

  auto preservePendingPage = [&]() {
    if (currentPage && !currentPage->elements.empty()) {
      pendingPage_ = std::move(currentPage);
      pendingPageY_ = currentPageY;
    }
  };

  auto addLineToPage = [&](std::shared_ptr<TextBlock> line) {
    if (!currentPage) {
      startNewPage();
    }

    if (currentPageY + lineHeight > config_.viewportHeight) {
      onPageComplete(std::move(currentPage));
      pagesCreated++;
      startNewPage();

      if (maxPages > 0 && pagesCreated >= maxPages) {
        currentPage->elements.push_back(std::make_unique<PageLine>(std::move(line), 0, currentPageY));
        currentPageY += lineHeight;
        return false;
      }
    }

    currentPage->elements.push_back(std::make_unique<PageLine>(std::move(line), 0, currentPageY));
    currentPageY += lineHeight;
    return true;
  };

  auto flushBlock = [&]() -> bool {
    if (!currentBlock || currentBlock->isEmpty()) return true;

    bool continueProcessing = true;
    currentBlock->layoutAndExtractLines(
        renderer_, config_.fontId, config_.viewportWidth,
        [&](const std::shared_ptr<TextBlock>& line) {
          if (!continueProcessing) return;
          if (!addLineToPage(line)) {
            continueProcessing = false;
          }
        },
        true, [&]() -> bool { return !continueProcessing; });

    if (continueProcessing) {
      currentBlock.reset();
    }
    // else: currentBlock still has unconsumed words — preserve it
    return continueProcessing;
  };

  if (currentOffset_ == 0) {
    const int peekResult = file.read(buffer, READ_CHUNK_SIZE);
    if (peekResult > 0) {
      const size_t peekBytes = static_cast<size_t>(peekResult);
      buffer[peekBytes] = '\0';
      isRtl_ = ScriptDetector::containsArabic(reinterpret_cast<const char*>(buffer));
    }
    file.seekSet(0);
  }

  if (pendingPage_) {
    currentPage = std::move(pendingPage_);
    currentPageY = pendingPageY_;
    pendingPageY_ = 0;
  } else {
    startNewPage();
  }

  // Resume: flush any pending block carried over from a previous interrupted batch
  if (pendingBlock_) {
    currentBlock = std::move(pendingBlock_);
    if (!flushBlock()) {
      // Still can't fit — save pending block and return
      pendingBlock_ = std::move(currentBlock);
      preservePendingPage();
      file.close();
      return true;
    }
  }

  if (!currentBlock) {
    currentBlock.reset(new ParsedText(static_cast<TextBlock::BLOCK_STYLE>(config_.paragraphAlignment),
                                      config_.indentLevel, config_.hyphenation, true, isRtl_));
  }

  while (file.available() > 0) {
    // Check for abort every few iterations
    if (shouldAbort && (++abortCheckCounter % 10 == 0) && shouldAbort()) {
      LOG_INF(TAG, "Aborted by external request");
      currentOffset_ = file.position();
      hasMore_ = true;
      file.close();
      return false;
    }

    const int readResult = file.read(buffer, READ_CHUNK_SIZE);
    if (readResult <= 0) {
      LOG_ERR(TAG, "File read error at offset %lu", static_cast<unsigned long>(file.position()));
      file.close();
      return false;
    }

    const size_t bytesRead = static_cast<size_t>(readResult);
    buffer[bytesRead] = '\0';

    for (size_t i = 0; i < bytesRead; i++) {
      char c = static_cast<char>(buffer[i]);

      // Handle newlines as paragraph breaks
      if (c == '\n') {
        // Flush partial word
        if (!partialWord.empty()) {
          partialWord.resize(utf8NormalizeNfc(&partialWord[0], partialWord.size()));
          currentBlock->addWord(partialWord, EpdFontFamily::REGULAR);
          partialWord.clear();
        }

        // Flush current block (paragraph)
        if (!flushBlock()) {
          // currentBlock still has unconsumed words — save for next call
          pendingBlock_ = std::move(currentBlock);
          // Keep the newline unread until the pending paragraph tail is laid
          // out.  The next batch will then apply paragraph spacing exactly
          // once after that tail completes.
          currentOffset_ = file.position() - (bytesRead - i);
          hasMore_ = true;
          file.close();

          preservePendingPage();
          return true;
        }

        // Start new paragraph
        currentBlock.reset(new ParsedText(static_cast<TextBlock::BLOCK_STYLE>(config_.paragraphAlignment),
                                          config_.indentLevel, config_.hyphenation, true, isRtl_));

        // Add paragraph spacing
        switch (config_.spacingLevel) {
          case 1:
            currentPageY += lineHeight / 4;
            break;
          case 3:
            currentPageY += lineHeight;
            break;
        }
        continue;
      }

      if (isWhitespace(c)) {
        if (!partialWord.empty()) {
          partialWord.resize(utf8NormalizeNfc(&partialWord[0], partialWord.size()));
          currentBlock->addWord(partialWord, EpdFontFamily::REGULAR);
          partialWord.clear();
        }
        continue;
      }

      partialWord += c;

      // Prevent extremely long words from accumulating
      if (partialWord.length() > 100) {
        // Back up to last valid UTF-8 codepoint boundary to avoid splitting multi-byte chars
        size_t safeLen = partialWord.length();
        while (safeLen > 0 && (static_cast<unsigned char>(partialWord[safeLen - 1]) & 0xC0) == 0x80) {
          safeLen--;
        }
        if (safeLen > 0 && static_cast<unsigned char>(partialWord[safeLen - 1]) >= 0xC0) {
          safeLen--;
        }

        if (safeLen > 0) {
          std::string overflow = partialWord.substr(safeLen);
          partialWord.resize(safeLen);
          partialWord.resize(utf8NormalizeNfc(&partialWord[0], partialWord.size()));
          currentBlock->addWord(partialWord, EpdFontFamily::REGULAR);
          partialWord = std::move(overflow);
        } else {
          partialWord.resize(utf8NormalizeNfc(&partialWord[0], partialWord.size()));
          currentBlock->addWord(partialWord, EpdFontFamily::REGULAR);
          partialWord.clear();
        }
      }
    }

    // Check if we hit max pages
    if (maxPages > 0 && pagesCreated >= maxPages) {
      currentOffset_ = file.position();
      preservePendingPage();
      hasMore_ = pendingPage_ || (currentOffset_ < fileSize_);
      file.close();
      return true;
    }
  }

  // Flush remaining content
  if (!partialWord.empty()) {
    partialWord.resize(utf8NormalizeNfc(&partialWord[0], partialWord.size()));
    currentBlock->addWord(partialWord, EpdFontFamily::REGULAR);
  }
  if (!flushBlock()) {
    pendingBlock_ = std::move(currentBlock);
    currentOffset_ = fileSize_;
    hasMore_ = true;
    preservePendingPage();
    file.close();
    return true;
  }

  // Complete final page
  if (currentPage && !currentPage->elements.empty()) {
    onPageComplete(std::move(currentPage));
    pagesCreated++;
  }

  file.close();
  currentOffset_ = fileSize_;
  hasMore_ = false;

  LOG_INF(TAG, "Parsed %d pages from %s", pagesCreated, filepath_.c_str());
  return true;
}
