#!/usr/bin/env python3
"""
Convert pre-generated .epdfont binary to C header (PROGMEM arrays).

Used to bake JetBrains Mono variants into the firmware without re-running
fontconvert.py (which requires freetype-py + network for setup).

Input file format documented in lib/EpdFont/src/EpdFontLoader.h:
  Header (16):  magic 'EPDF' + version u16 + flags u16 + 8 bytes reserved
  Metrics (18): advanceY u8 + pad u8 + ascender i16 + descender i16
                + intervalCount u32 + glyphCount u32 + bitmapSize u32
  Intervals: intervalCount * (first u32, last u32, offset u32)
  Glyphs:    glyphCount * (width u8, height u8, advanceX u8, pad u8,
                           left i16, top i16, dataLength u16, dataOffset u32)
  Bitmap:    bitmapSize bytes
"""
import argparse
import struct
import sys
import unicodedata
from pathlib import Path

OFL_HEADER = """/*
 * SIL OPEN FONT LICENSE 1.1 — bundled font notice (required by §56-61).
 *
 * Based on JetBrains Mono NL by JetBrains s.r.o.
 * Copyright 2020 The JetBrains Mono Project Authors
 *   (https://github.com/JetBrains/JetBrainsMono)
 *
 * This font is licensed under the SIL Open Font License, Version 1.1.
 * Full license text: scripts/jetbrains/OFL.txt (also bundled with each
 * snapix release archive).  License URL: https://openfontlicense.org
 *
 * Embedded in the snapix firmware as a derivative work — format conversion
 * (TTF → .epdfont → C array) is permitted under OFL §39-42.
 */
"""


def safe_glyph_comment(cp: int) -> str:
    """Return a short, safe glyph annotation for the C comment."""
    if cp == 0:
        return ""
    if cp == 0xFFFD:
        return "REPLACEMENT"
    try:
        ch = chr(cp)
    except ValueError:
        return f"U+{cp:04X}"
    cat = unicodedata.category(ch)
    # Suppress control / format / unassigned / surrogate categories that
    # would render as garbage or break some terminals when the C file is
    # opened in the IDE.
    if cat[0] in ("C", "Z") and cp != 0x20:
        return f"U+{cp:04X}"
    return ch


def parse_epdfont(buf: bytes):
    if buf[:4] != b"EPDF":
        raise ValueError("not an EPDF file (bad magic)")
    version, flags = struct.unpack_from("<HH", buf, 4)
    if version != 1:
        raise ValueError(f"unsupported version {version}")
    is_2bit = bool(flags & 0x1)
    pos = 16

    # FileMetrics (packed, 18 bytes total)
    advance_y, _pad, ascender, descender, interval_count, glyph_count, bitmap_size = struct.unpack_from(
        "<BBhhIII", buf, pos
    )
    pos += struct.calcsize("<BBhhIII")

    intervals = []
    for _ in range(interval_count):
        first, last, offset = struct.unpack_from("<III", buf, pos)
        intervals.append((first, last, offset))
        pos += 12

    glyphs = []
    for _ in range(glyph_count):
        width, height, advance_x, _gpad, left, top, data_length, data_offset = struct.unpack_from(
            "<BBBBhhHI", buf, pos
        )
        glyphs.append((width, height, advance_x, left, top, data_length, data_offset))
        pos += 14

    bitmap = buf[pos : pos + bitmap_size]
    if len(bitmap) != bitmap_size:
        raise ValueError(f"bitmap truncated: {len(bitmap)} != {bitmap_size}")

    return {
        "is_2bit": is_2bit,
        "advance_y": advance_y,
        "ascender": ascender,
        "descender": descender,
        "intervals": intervals,
        "glyphs": glyphs,
        "bitmap": bitmap,
    }


def derive_glyph_codepoint(glyph_index: int, intervals):
    """Map a glyph index back to its starting codepoint via interval table."""
    cumulative = 0
    for first, last, offset in intervals:
        run_len = last - first + 1
        if offset <= glyph_index < offset + run_len:
            return first + (glyph_index - offset)
        cumulative = max(cumulative, offset + run_len)
    return 0xFFFD


def emit_header(font_name: str, data, output_path: Path):
    out = [OFL_HEADER]
    out.append(f"/**\n * generated by epdfont_to_header.py\n * name: {font_name}\n")
    out.append(f" * mode: {'2-bit' if data['is_2bit'] else '1-bit'}\n */\n")
    out.append("#pragma once\n#include \"EpdFontData.h\"\n\n")

    bitmap = data["bitmap"]
    out.append(f"static const uint8_t PROGMEM {font_name}Bitmaps[{len(bitmap)}] = {{\n    ")
    for i in range(0, len(bitmap), 19):
        chunk = bitmap[i : i + 19]
        out.append(", ".join(f"0x{b:02X}" for b in chunk))
        if i + 19 < len(bitmap):
            out.append(",\n    ")
    out.append("\n};\n\n")

    intervals = data["intervals"]
    out.append(f"static const EpdGlyph PROGMEM {font_name}Glyphs[] = {{\n")
    for idx, (w, h, ax, left, top, dl, do) in enumerate(data["glyphs"]):
        cp = derive_glyph_codepoint(idx, intervals)
        comment = safe_glyph_comment(cp)
        out.append(
            f"    {{{w}, {h}, {ax}, {left}, {top}, {dl}, {do}}},  // {comment}\n"
        )
    out.append("};\n\n")

    out.append(f"static const EpdUnicodeInterval PROGMEM {font_name}Intervals[] = {{\n")
    for i, (first, last, offset) in enumerate(intervals):
        out.append(f"    {{0x{first:X}, 0x{last:X}, 0x{offset:X}}},")
        if (i + 1) % 4 == 0 or i == len(intervals) - 1:
            out.append("\n")
        else:
            out.append(" ")
    out.append("};\n\n")

    out.append(
        f"static const EpdFontData {font_name} = {{\n"
        f"    {font_name}Bitmaps, {font_name}Glyphs, {font_name}Intervals, "
        f"{len(intervals)}, {data['advance_y']}, {data['ascender']}, "
        f"{data['descender']}, {'true' if data['is_2bit'] else 'false'},\n}};\n"
    )
    output_path.write_text("".join(out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=Path, help="input .epdfont file")
    ap.add_argument("name", help="C identifier name, e.g. jetbrains_mono_12_2b")
    ap.add_argument("-o", "--output", type=Path, required=True, help="output .h path")
    args = ap.parse_args()

    buf = args.input.read_bytes()
    data = parse_epdfont(buf)
    emit_header(args.name, data, args.output)
    bitmap_kb = len(data["bitmap"]) / 1024
    glyph_count = len(data["glyphs"])
    interval_count = len(data["intervals"])
    print(
        f"{args.input.name} → {args.output.name}: "
        f"{bitmap_kb:.1f}KB bitmap, {glyph_count} glyphs, "
        f"{interval_count} intervals, "
        f"{'2-bit' if data['is_2bit'] else '1-bit'}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
